plugins:
  mumble_enabled:
    default: true
    client: true
  mumble_cvp:
    default: ''
  mumble_xml:
    default: false
  mumble_afkchannel:
    default: ''
    client: true
  mumble_server_ui_connect_path:
    default: ''
    client: true
  mumble_server_ui_connect_port:
    default: 0
    client: true
